vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set("n", "<Tab>", "o<Esc>")
vim.keymap.set("n", "<S-Tab>", "ddk<Esc>")
vim.keymap.set("n", "<Leader>t", "<Cmd>ToggleTerm<CR>")
vim.keymap.set("n", "<C-b>", "<Cmd>NvimTreeToggle<CR>")
vim.keymap.set("n", "<C-s>", "<Cmd>Oil<CR>")
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")
vim.keymap.set("t", "jk", "<C-\\><C-n>")
vim.keymap.set("n", "<Leader>f", "<Cmd>tabnew %<CR>")
vim.keymap.set("n", "<Esc>", "<Cmd>nohlsearch<CR>")
vim.keymap.set("n", "i", "<Cmd>nohlsearch<CR>i")
vim.keymap.set("n", "a", "<Cmd>nohlsearch<CR>a")
vim.keymap.set("n", "o", "<Cmd>nohlsearch<CR>o")
vim.keymap.set("n", "<Leader>h", "<C-w><C-h>", { desc = "Move focus to the left window" })
vim.keymap.set("n", "<Leader>l", "<C-w><C-l>", { desc = "Move focus to the right window" })
vim.keymap.set("n", "<Leader>k", "<C-w><C-k>", { desc = "Move focus to the upper window" })
vim.keymap.set("n", "<Leader>j", "<C-w><C-j>", { desc = "Move focus to the lower window" })
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("v", "<C-H>", "<gv")
vim.keymap.set("v", "<C-L>", ">gv")
vim.keymap.set("n", "<C-a>", require("custom_plugin.quickcmd.quickcmd").run_cmd)
vim.keymap.set("n", "gf", require("custom_plugin.gf").get_link_under_cursor)
vim.keymap.set("v", "gf", require("custom_plugin.gf").get_link_under_selection)
vim.g.VM_maps = {
    ["Select Cursor Down"] = "<C-j>",
    ["Select Cursor Up"] = "<C-k>",
    ["Find Under"] = "<C-d>",
}
vim.keymap.set("n", "<Leader>n", "<Cmd>ASToggle<CR>")
vim.keymap.set("n", "j", "gj", { silent = true })
vim.keymap.set("n", "k", "gk", { silent = true })
vim.keymap.set("n", "K", function()
    require("lsp_signature").toggle_float_win()
end)
