vim.keymap.set("i", "jk", "<Esc>")
vim.keymap.set("n", "<Tab>", "o<Esc>")
vim.keymap.set("n", "<S-Tab>", "ddk<Esc>")
-- vim.keymap.set("n", "<C-b>", "<Cmd>NvimTreeToggle<CR>")
-- vim.keymap.set("n", "<C-b>", "<Cmd>CHADopen<CR>")
-- vim.keymap.set("n", "<C-b>", "<Cmd>Oil .<CR>")
vim.keymap.set("n", "<C-b>", "<Cmd>Dired<CR>")
vim.keymap.set("n", "<C-A-b>", function()
    local dir = vim.fn.input("Directory: ", "", "file")
    vim.cmd("Dired " .. dir)
end)
vim.keymap.set("t", "jk", "<C-\\><C-n>")
vim.keymap.set("n", "<Leader>f", "<Cmd>tabnew %<CR>")
vim.keymap.set("n", "<Esc>", "<Cmd>nohlsearch<CR>")
vim.keymap.set("n", "i", "<Cmd>nohlsearch<CR>i")
vim.keymap.set("n", "a", "<Cmd>nohlsearch<CR>a")
vim.keymap.set("n", "o", "<Cmd>nohlsearch<CR>o")
vim.keymap.set("n", "<Leader>h", "<C-w><C-h>", { desc = "Move focus to the left window" })
vim.keymap.set("n", "<Leader>l", "<C-w><C-l>", { desc = "Move focus to the right window" })
vim.keymap.set("n", "<Leader>k", "<C-w><C-k>", { desc = "Move focus to the upper window" })
vim.keymap.set("n", "<Leader>j", "<C-w><C-j>", { desc = "Move focus to the lower window" })
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("v", "<C-H>", "<gv")
vim.keymap.set("v", "<C-L>", ">gv")
vim.keymap.set("v", "p", '"_dP')
vim.keymap.set("n", "<Leader>p", require("custom_plugin.quickcmd.quickcmd").run_cmd)
vim.keymap.set("n", "gf", require("custom_plugin.gf").get_link_under_cursor)
vim.keymap.set("v", "gf", require("custom_plugin.gf").get_link_under_selection)
vim.g.VM_maps = {
    ["Select Cursor Down"] = "<C-j>",
    ["Select Cursor Up"] = "<C-k>",
    ["Find Under"] = "<C-d>",
    ["Find Subword Under"] = "<C-d>",
}
vim.keymap.set("n", "<Leader>n", "<Cmd>ASToggle<CR>")
vim.keymap.set("n", "j", "gj", { silent = true })
vim.keymap.set("n", "k", "gk", { silent = true })
-- vim.keymap.set("n", "L", function()
--     require("lsp_signature").toggle_float_win()
-- end)
vim.keymap.set("n", "K", function()
    vim.lsp.buf.hover()
end)
vim.keymap.set("n", "N", function()
    vim.diagnostic.open_float()
end)
vim.keymap.set("n", "M", "<Cmd>Man<CR>")
vim.keymap.set("n", "<A-l>", "<C-w><")
vim.keymap.set("n", "<A-h>", "<C-w>>")
vim.keymap.set("n", "<A-j>", "<C-w>-")
vim.keymap.set("n", "<A-k>", "<C-w>+")
vim.keymap.set("n", "<C-l>", function()
    require("nvim-window").pick()
end)
vim.keymap.set("n", "<Leader>dt", function()
    require("dapui").toggle()
end, { desc = "[D]ebug [T]oggle" })
vim.keymap.set("n", "<Leader>db", "<Cmd>DapToggleBreakpoint<CR>", { desc = "[D]ebug [B]reakpoint" })
vim.keymap.set("n", "<Leader>dc", "<Cmd>DapContinue<CR>", { desc = "[D]ebug [C]ontinue" })
vim.keymap.set("n", "<Leader>ds", "<Cmd>DapStepOver<CR>", { desc = "[D]ebug [S]tep" })
vim.keymap.set("n", "<Leader>g", "<Cmd>Neogit<CR>", { desc = "Open git" })
vim.keymap.set("n", "<C-f>", function()
    require("conform").format({ async = true, lsp_fallback = true })
end)
vim.keymap.set("n", "<Leader>cn", "<Cmd>cn<CR>")
vim.keymap.set("n", "<Leader>cp", "<Cmd>cp<CR>")
vim.keymap.set("n", "<C-[>", function()
    vim.api.nvim_command("ToggleTerm direction=vertical size=" .. (vim.o.columns / 3))
end)
vim.keymap.set("t", "<C-[>", "<Cmd>ToggleTerm<CR>")
